# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '0 1 * * *'
  watch:
    types: started

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: set git config 
      run: |
        git config --global user.name "sohyunQVQ[bot]"
        git config --global user.email "abigeater@163.com"
    - name: git pull erp
      run: |
        git pull
    - name: run srcipt
      run: |
        python 163music.py 136164194 1
    - name: commit to rep
      run: |
        git add README.md
        git commit -m "Update README.md"
        git push